name: PHP Lint

on:
  push:
  pull_request:

jobs:
  php-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          extensions: mysqli

      - name: Lint PHP files
        run: |
          find . -name "*.php" -not -path "./vendor/*" -print0 \
            | xargs -0 -n1 php -l
